apiVersion: apps/v1
kind: Deployment
metadata:
    name: web
spec: 
   template:
      metadata:
          name: nginx-pod
          labels: 
             app: frontend
      spec: 
         containers:
             - name: nginx
               image: nginx:1.18.1
               ports:
                - name: frontend-port 
                  containerPort: 80
   replicas: 3
   selector:
        matchLabels:
             app: frontend 

