apiVersion: apps/v1
kind: Deployment
metadata:
      name: vproapp-deployment
spec:
   template:
       metadata:
           name: vproapp-pod
           labels:
               app: vprofile
       spec:         
          containers:
                - name: vproapp-container
                  image: krunaldahake123/vprofileapp:v1
                  ports:
                      - containerPort: 8080
                  command:
                    - chown
                    - -R
                    - 472:472
                    - /usr/local/tomcat 
                  volumeMounts:
                        - mountPath: /usr/local/tomcat
                          name: mydb      
          volumes:
              - name: mydb 
                hostPath:
                     path: /data
                     type: DirectoryOrCreate           
   replicas: 3
   selector:
         matchLabels:
              app: vprofile                      
