apiVersion: apps/v1
kind: Deployment
metadata:
      name: vproapp-deployment
spec:
   template:
       metadata:
           name: vproapp-pod
           labels:
               app: vprofile
       containers:
             - name: vproapp-container
               image: krunaldahake123/vprofileapp:v1
               ports:
                   containerPort: 8080    
                  
   replicas: 3
   selector:
         matchLabels:
              app: vprofile                      
