apiVersion: v1
kind: Service
metadata:
    name: frontend
spec:
  ports:
     - port: 80
       targetPort: 8080
       nodePort: 30001
       protocol: TCP
  type:
     NodePort
  selector:
    app: vrpoapp              