apiVersion: v1
kind: Service
metadata:
    name: frontend
spec:
  ports:
     - port: 80
       nodePort: 30001
       targetPort: 8080
       protocol: TCP
  selector:
    app: vproapp      
  type:
     NodePort
               