apiVersion: v1
kind: Service
metadata:
     name: vrpoapp-expose
spec: 
   ports:
      - port: 3000
        nodePort: 3020
        targetPort: 8080
        protocol: TCP
   selector:
       app: vprofile
   type: NodePort    